/**
 * Install jev-router into Oh My Pi's native extension directory.
 *
 * OMP auto-discovers every `.ts` under `<agentDir>/extensions`, so the install
 * is one generated shim file that re-exports this repo's extension by absolute
 * path — the same approach jev-gate uses. A shim (rather than a copy) means an
 * edit in the repo takes effect on the next session with no reinstall.
 *
 *   bun scripts/install.ts            # write/refresh the shim
 *   bun scripts/install.ts --uninstall
 *
 * The marketplace route (`omp plugin link <this dir>`) is equivalent and
 * additionally exposes the plugin to `/marketplace`; both can coexist.
 */

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = dirname(dirname(fileURLToPath(import.meta.url)));
const EXTENSION = join(REPO, "extensions", "jev-router.ts").replace(/\\/g, "/");
const AGENT_DIR = process.env.PI_CODING_AGENT_DIR ?? join(homedir(), ".omp", "agent");
const SHIM = join(AGENT_DIR, "extensions", "jev-router.ts");

const shimSource = `// Generated by jev-router/scripts/install.ts — edits belong in the repo.\nexport { default } from "${EXTENSION}";\n`;

if (process.argv.includes("--uninstall")) {
	if (existsSync(SHIM) && readFileSync(SHIM, "utf8").includes("Generated by jev-router")) {
		rmSync(SHIM);
		console.log(`removed ${SHIM}`);
	} else {
		console.log(`nothing to remove at ${SHIM}`);
	}
} else {
	mkdirSync(dirname(SHIM), { recursive: true });
	writeFileSync(SHIM, shimSource);
	console.log(`installed ${SHIM}\n        -> ${EXTENSION}`);
	console.log("\nRestart OMP (or run /reload) so the extension loads. Verify with: /jev-router status");
}
